--
-- PostgreSQL database dump
--

\restrict l8wi4RYriBHmKGOce3yZ9rSgIF4e7FOfosL4gCHOHh2o0J0fC3qYlivZCgf61Es

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg13+1)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat_conversation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_conversation (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    admin_user_id integer NOT NULL,
    partner_id bigint NOT NULL,
    client_user_id bigint
);


--
-- Name: chat_conversation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_conversation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_conversation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_message (
    id bigint NOT NULL,
    content text NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    receiver_id integer NOT NULL,
    sender_id integer NOT NULL
);


--
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: chat_conversation; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.chat_conversation (id, created_at, updated_at, admin_user_id, partner_id, client_user_id) FROM stdin;
4	2026-03-12 09:24:04.502985+00	2026-03-13 12:59:42.170445+00	3	84	\N
6	2026-03-16 10:54:42.564043+00	2026-04-11 10:55:59.637432+00	1	111	\N
8	2026-04-11 12:29:20.891077+00	2026-04-11 12:29:20.89112+00	1	562	\N
5	2026-03-14 12:13:00.027799+00	2026-03-15 18:56:43.087294+00	3	198	\N
3	2026-03-09 08:19:28.296618+00	2026-03-19 08:37:07.639966+00	3	111	\N
\.


--
-- Data for Name: chat_message; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.chat_message (id, content, is_read, created_at, updated_at, receiver_id, sender_id) FROM stdin;
\.


--
-- Name: chat_conversation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.chat_conversation_id_seq', 8, true);


--
-- Name: chat_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.chat_message_id_seq', 1, false);


--
-- Name: chat_conversation chat_conversation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversation
    ADD CONSTRAINT chat_conversation_pkey PRIMARY KEY (id);


--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- Name: chat_conversation unique_admin_partner_conversation; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversation
    ADD CONSTRAINT unique_admin_partner_conversation UNIQUE (admin_user_id, partner_id);


--
-- Name: chat_conver_admin_u_14821f_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_conver_admin_u_14821f_idx ON public.chat_conversation USING btree (admin_user_id, updated_at DESC);


--
-- Name: chat_conver_partner_d729da_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_conver_partner_d729da_idx ON public.chat_conversation USING btree (partner_id, updated_at DESC);


--
-- Name: chat_conversation_admin_user_id_b7f3c27f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_conversation_admin_user_id_b7f3c27f ON public.chat_conversation USING btree (admin_user_id);


--
-- Name: chat_conversation_partner_id_59be5e4a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_conversation_partner_id_59be5e4a ON public.chat_conversation USING btree (partner_id);


--
-- Name: chat_messag_created_f18bb8_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_messag_created_f18bb8_idx ON public.chat_message USING btree (created_at DESC);


--
-- Name: chat_messag_receive_14362e_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_messag_receive_14362e_idx ON public.chat_message USING btree (receiver_id, is_read);


--
-- Name: chat_messag_sender__61a5fc_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_messag_sender__61a5fc_idx ON public.chat_message USING btree (sender_id, receiver_id);


--
-- Name: chat_message_receiver_id_0eceddde; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_message_receiver_id_0eceddde ON public.chat_message USING btree (receiver_id);


--
-- Name: chat_message_sender_id_991c686c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_message_sender_id_991c686c ON public.chat_message USING btree (sender_id);


--
-- Name: chat_conversation chat_conversation_admin_user_id_b7f3c27f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversation
    ADD CONSTRAINT chat_conversation_admin_user_id_b7f3c27f_fk_auth_user_id FOREIGN KEY (admin_user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_conversation chat_conversation_partner_id_59be5e4a_fk_users_partner_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversation
    ADD CONSTRAINT chat_conversation_partner_id_59be5e4a_fk_users_partner_id FOREIGN KEY (partner_id) REFERENCES public.users_partner(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_message chat_message_receiver_id_0eceddde_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_receiver_id_0eceddde_fk_auth_user_id FOREIGN KEY (receiver_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_message chat_message_sender_id_991c686c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_sender_id_991c686c_fk_auth_user_id FOREIGN KEY (sender_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict l8wi4RYriBHmKGOce3yZ9rSgIF4e7FOfosL4gCHOHh2o0J0fC3qYlivZCgf61Es

