PMS_PROPERTY_TABLE = "pms_property"
PMS_PROPERTY_IMAGE_TABLE = "pms_property_image"
PMS_ROOM_TABLE = "pms_room"
PMS_CALENDAR_SLOT_TABLE = "pms_calendar_slot"
PMS_GUEST_TABLE = "pms_guest"
PMS_BOOKING_TABLE = "pms_booking"
PMS_BOOKING_HISTORY_TABLE = "pms_booking_history"
PMS_REVIEW_TABLE = "pms_review"
