"""Emit the DDL for the raw-SQL tables, read from a live database.

Most of this project's tables are not Django models: they are raw SQL created
by hand, and their definition exists only inside whatever database is running.
That is why a fresh database cannot be built from the repository, why the two
tenant-provisioning paths drifted apart unnoticed, and why the endpoint smoke
suite cannot run in CI.

This command reads the real shape out of a database and prints it as
re-appliable SQL. Run it against staging (or a restored dump), commit the
result, and `bootstrap_schema` can then rebuild the schema anywhere.

    python manage.py dump_raw_schema > schema/public_baseline.sql
    python manage.py dump_raw_schema --schema tenant_ab12 > schema/tenant_baseline.sql

Django-managed tables are skipped by default: `manage.py migrate` owns those,
and duplicating them here would create two sources of truth for the same
tables — the exact problem this command exists to end.
"""
from __future__ import annotations

from django.core.management.base import BaseCommand, CommandError
from django.db import connection

# Owned by `migrate`, not by this dump.
DJANGO_TABLE_PREFIXES = (
    "django_",
    "auth_",
    "recommendation_",  # apps/recommendation/migrations/0001_initial.py
)
DJANGO_TABLE_NAMES = {
    "client_embeddings",
    "property_embeddings",
    "recommendation_graph",
}

# Created by `CREATE EXTENSION`, not by us. Dumping them produces a file that
# fights the extension when it is applied.
EXTENSION_TABLE_NAMES = {
    "spatial_ref_sys",  # postgis
}


class Command(BaseCommand):
    help = "Print CREATE TABLE/INDEX statements for the raw-SQL tables in a schema."

    def add_arguments(self, parser):
        parser.add_argument(
            "--schema",
            default="public",
            help="Schema to read (default: public).",
        )
        parser.add_argument(
            "--include-django",
            action="store_true",
            help="Also dump tables that Django migrations own (normally skipped).",
        )
        parser.add_argument(
            "--table",
            action="append",
            default=[],
            help="Dump only this table. Repeatable.",
        )
        parser.add_argument(
            "--output",
            help=(
                "Write the SQL here instead of stdout. Prefer this: the project's "
                "JSON logging also writes to stdout, so a shell redirect captures "
                "log lines into the middle of the file."
            ),
        )

    def handle(self, *args, **options):
        schema = options["schema"]
        only = set(options["table"])

        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM information_schema.schemata WHERE schema_name = %s",
                [schema],
            )
            if cursor.fetchone() is None:
                raise CommandError(f"Schema '{schema}' does not exist in this database.")

            tables = [
                t for t in self._tables(cursor, schema)
                if t not in EXTENSION_TABLE_NAMES
            ]
            if only:
                missing = only - set(tables)
                if missing:
                    raise CommandError(
                        f"Not found in '{schema}': {', '.join(sorted(missing))}"
                    )
                tables = [t for t in tables if t in only]
            if not options["include_django"]:
                tables = [t for t in tables if not self._is_django_owned(t)]

            out = [
                "-- Generated by `manage.py dump_raw_schema`. Do not hand-edit:",
                "-- regenerate it from a database that is known good.",
                f"-- schema: {schema}    tables: {len(tables)}",
                "",
            ]

            for table in tables:
                out.append(self._create_table(cursor, schema, table))
                out.append("")

            # Indexes come after every table exists, and foreign keys after
            # every index — otherwise the file cannot be applied top to bottom.
            index_sql = [s for t in tables for s in self._indexes(cursor, schema, t)]
            if index_sql:
                out += ["-- ─── Indexes ───", ""] + index_sql + [""]

            fk_sql = [s for t in tables for s in self._foreign_keys(cursor, schema, t)]
            if fk_sql:
                out += ["-- ─── Foreign keys ───", ""] + fk_sql + [""]

        sql = "\n".join(out)
        destination = options.get("output")
        if destination:
            with open(destination, "w", encoding="utf-8") as handle:
                handle.write(sql + "\n")
            self.stderr.write(f"Wrote {len(tables)} tables to {destination}")
        else:
            self.stdout.write(sql)

    @staticmethod
    def _is_django_owned(table: str) -> bool:
        return table in DJANGO_TABLE_NAMES or table.startswith(DJANGO_TABLE_PREFIXES)

    @staticmethod
    def _tables(cursor, schema: str) -> list[str]:
        cursor.execute(
            """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = %s AND table_type = 'BASE TABLE'
            ORDER BY table_name
            """,
            [schema],
        )
        return [row[0] for row in cursor.fetchall()]

    def _create_table(self, cursor, schema: str, table: str) -> str:
        cursor.execute(
            """
            SELECT column_name, data_type, character_maximum_length,
                   numeric_precision, numeric_scale, is_nullable,
                   column_default, udt_name
            FROM information_schema.columns
            WHERE table_schema = %s AND table_name = %s
            ORDER BY ordinal_position
            """,
            [schema, table],
        )
        columns = [self._column(row) for row in cursor.fetchall()]

        pk = self._primary_key(cursor, schema, table)
        if pk:
            quoted = ", ".join(f'"{col}"' for col in pk)
            columns.append(f"PRIMARY KEY ({quoted})")
        columns += self._unique_constraints(cursor, schema, table)

        body = ",\n    ".join(columns)
        return f'CREATE TABLE IF NOT EXISTS "{table}" (\n    {body}\n);'

    @staticmethod
    def _column(row) -> str:
        (name, data_type, char_len, num_precision, num_scale,
         nullable, default, udt) = row

        if data_type == "ARRAY":
            # udt_name for an array is the element type prefixed with '_'.
            sql_type = f"{udt.lstrip('_')}[]"
        elif data_type == "character varying":
            sql_type = f"VARCHAR({char_len})" if char_len else "VARCHAR"
        elif data_type == "character":
            sql_type = f"CHAR({char_len})" if char_len else "CHAR"
        elif data_type == "numeric" and num_precision is not None:
            sql_type = f"NUMERIC({num_precision},{num_scale or 0})"
        elif data_type == "USER-DEFINED":
            sql_type = udt
        else:
            sql_type = data_type.upper()

        # Quoted throughout: real column names here include reserved words
        # such as `order`, which break an unquoted CREATE TABLE.
        quoted_name = f'"{name}"'

        # A serial column is an integer whose default is a sequence; reproduce
        # it as BIGSERIAL/SERIAL so the sequence is recreated with the table.
        if default and default.startswith("nextval("):
            if data_type == "bigint":
                return f"{quoted_name} BIGSERIAL"
            if data_type == "integer":
                return f"{quoted_name} SERIAL"
            if data_type == "smallint":
                return f"{quoted_name} SMALLSERIAL"

        parts = [quoted_name, sql_type]
        if nullable == "NO":
            parts.append("NOT NULL")
        if default and not default.startswith("nextval("):
            parts.append(f"DEFAULT {default}")
        return " ".join(parts)

    @staticmethod
    def _primary_key(cursor, schema: str, table: str) -> list[str]:
        cursor.execute(
            """
            SELECT a.attname
            FROM pg_index i
            JOIN pg_class c ON c.oid = i.indrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ANY(i.indkey)
            WHERE n.nspname = %s AND c.relname = %s AND i.indisprimary
            ORDER BY array_position(i.indkey, a.attnum)
            """,
            [schema, table],
        )
        return [row[0] for row in cursor.fetchall()]

    @staticmethod
    def _unique_constraints(cursor, schema: str, table: str) -> list[str]:
        cursor.execute(
            """
            SELECT con.conname, pg_get_constraintdef(con.oid)
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = %s AND c.relname = %s AND con.contype = 'u'
            ORDER BY con.conname
            """,
            [schema, table],
        )
        return [definition for _name, definition in cursor.fetchall()]

    @staticmethod
    def _indexes(cursor, schema: str, table: str) -> list[str]:
        cursor.execute(
            """
            SELECT indexdef
            FROM pg_indexes
            WHERE schemaname = %s AND tablename = %s
            ORDER BY indexname
            """,
            [schema, table],
        )
        out = []
        for (indexdef,) in cursor.fetchall():
            # Primary-key and unique-constraint indexes are already part of the
            # CREATE TABLE above; re-issuing them would fail.
            if " USING " not in indexdef:
                continue
            if indexdef.startswith("CREATE UNIQUE INDEX") and "_pkey" in indexdef:
                continue
            statement = indexdef.replace(
                "CREATE INDEX ", "CREATE INDEX IF NOT EXISTS ", 1
            ).replace(
                "CREATE UNIQUE INDEX ", "CREATE UNIQUE INDEX IF NOT EXISTS ", 1
            )
            out.append(f"{statement};")
        return out

    @staticmethod
    def _foreign_keys(cursor, schema: str, table: str) -> list[str]:
        cursor.execute(
            """
            SELECT con.conname, pg_get_constraintdef(con.oid)
            FROM pg_constraint con
            JOIN pg_class c ON c.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = %s AND c.relname = %s AND con.contype = 'f'
            ORDER BY con.conname
            """,
            [schema, table],
        )
        out = []
        for name, definition in cursor.fetchall():
            # Re-running the file must not fail on constraints that already
            # exist, and IF NOT EXISTS is not available for ADD CONSTRAINT.
            out.append(
                f"DO $$ BEGIN\n"
                f'    ALTER TABLE "{table}" ADD CONSTRAINT "{name}" {definition};\n'
                f"EXCEPTION WHEN duplicate_object THEN NULL;\n"
                f"END $$;"
            )
        return out
