# Generated by Django 5.2.9 on 2026-02-19 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('property', '0002_remove_propertyreview_unique_client_property_review'),
        ('users', '0006_remove_client_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DELETE FROM property_propertyimage
            WHERE deleted_at IS NOT NULL
               OR property_id IN (
                    SELECT id
                    FROM property_property
                    WHERE deleted_at IS NOT NULL
               );
            DELETE FROM property_propertyprice
            WHERE deleted_at IS NOT NULL
               OR property_id IN (
                    SELECT id
                    FROM property_property
                    WHERE deleted_at IS NOT NULL
               );
            DELETE FROM property_propertyreview
            WHERE deleted_at IS NOT NULL
               OR property_id IN (
                    SELECT id
                    FROM property_property
                    WHERE deleted_at IS NOT NULL
               );
            DELETE FROM property_propertydetail
            WHERE deleted_at IS NOT NULL
               OR property_id IN (
                    SELECT id
                    FROM property_property
                    WHERE deleted_at IS NOT NULL
               );
            DELETE FROM property_propertyroom
            WHERE deleted_at IS NOT NULL
               OR property_id IN (
                    SELECT id
                    FROM property_property
                    WHERE deleted_at IS NOT NULL
               );
            DELETE FROM property_property_property_services
            WHERE property_id IN (
                SELECT id
                FROM property_property
                WHERE deleted_at IS NOT NULL
            );
            DELETE FROM property_property WHERE deleted_at IS NOT NULL;
            DELETE FROM property_propertylocation
            WHERE deleted_at IS NOT NULL
              AND NOT EXISTS (
                  SELECT 1
                  FROM property_property p
                  WHERE p.property_location_id = property_propertylocation.id
              );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveConstraint(
            model_name='property',
            name='unique_active_title',
        ),
        migrations.RemoveConstraint(
            model_name='property',
            name='unique_active_property_location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertydetail',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertylocation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertyprice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertyreview',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='propertyroom',
            name='deleted_at',
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('title',), name='unique_active_title'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('property_location',), name='unique_active_property_location'),
        ),
    ]
