# Generated by Django 5.2.9 on 2026-03-10 06:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_unique_active_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title_uz', models.CharField(default='', max_length=100, verbose_name='Title (uz)')),
                ('title_ru', models.CharField(default='', max_length=100, verbose_name='Title (ru)')),
                ('title_en', models.CharField(default='', max_length=100, verbose_name='Title (en)')),
                ('icon', models.FileField(blank=True, null=True, upload_to='property/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title_uz'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Title (uz)')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Title (ru)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title (en)')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['region', 'title_uz'],
            },
        ),
        migrations.CreateModel(
            name='Mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title_uz', models.CharField(max_length=150, unique=True, verbose_name='Title (uz)')),
                ('title_ru', models.CharField(blank=True, max_length=150, verbose_name='Title (ru)')),
                ('title_en', models.CharField(blank=True, max_length=150, verbose_name='Title (en)')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallas',
                'ordering': ['title_uz'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Title (uz)')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Title (ru)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title (en)')),
                ('img', models.ImageField(blank=True, null=True, upload_to='property/regions/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['title_uz'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='property/covers/', verbose_name='Cover image'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_recommended',
            field=models.BooleanField(db_default=False, default=False, help_text='Show in «Recommended places» block on main page', verbose_name='Recommended (Рекомендуемые места)'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_sort',
            field=models.CharField(blank=True, default='', help_text='Filled automatically from title if empty.', max_length=255, verbose_name='Title (for sorting)'),
        ),
        migrations.AddField(
            model_name='property',
            name='verification_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], db_default='waiting', default='waiting', max_length=10, verbose_name='Verification status'),
        ),
        migrations.AddField(
            model_name='property',
            name='weekend_only_sunday_inclusive',
            field=models.BooleanField(db_default=False, default=False, help_text='If set, customers can only book with check-in on Friday or Saturday, and the stay must include Sunday (check-out on Monday or later).', verbose_name='Weekend only, Sunday inclusive'),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apartment number'),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='entrance_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Entrance number'),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='floor_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Floor number'),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='home_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Home number'),
        ),
        migrations.AddField(
            model_name='propertydetail',
            name='pass_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pass code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(blank=True, db_default=False, default=False, null=True, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='property',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified at'),
        ),
        migrations.AlterField(
            model_name='property',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verified by'),
        ),
        migrations.AlterField(
            model_name='propertyservice',
            name='icon',
            field=models.FileField(upload_to='property/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='icon',
            field=models.FileField(upload_to='property/icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='property',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='properties', to='property.category', verbose_name='Categories (Свежие предложения)'),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='property.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='property',
            name='mahalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='property.mahalla', verbose_name='Mahalla'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='property.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='property.region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='Shaharcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Title (uz)')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Title (ru)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title (en)')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaharchas', to='property.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Shaharcha',
                'verbose_name_plural': 'Shaharchas',
                'ordering': ['district', 'title_uz'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='shaharcha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='property.shaharcha', verbose_name='Shaharcha'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('region', 'title_uz'), name='unique_region_district_uz'),
        ),
        migrations.AddConstraint(
            model_name='shaharcha',
            constraint=models.UniqueConstraint(fields=('district', 'title_uz'), name='unique_district_shaharcha_uz'),
        ),
    ]
