from django.urls import path

from .views import (
    PropertyCalendarDateListView,
    PropertyCalendarDateBlockView,
    PropertyCalendarDateUnblockView,
    PropertyCalendarDateHoldView,
    PropertyCalendarDateUnholdView,
    ClientBookingListCreateView,
    ClientBookingCancelView,
    PartnerBookingAcceptView,
    PartnerBookingCancelView,
    PartnerBookingListView,
    PartnerCompleteBookingView,
    PartnerNoShowBookingView,
    ClientBookingDetailView,
    ClientBookingHistoryDetailView,
    ClientBookingHistoryListView,
    AdminBookingListView,
)

urlpatterns = [
    path(
        "properties/<uuid:property_id>/calendar/",
        PropertyCalendarDateListView.as_view(),
        name="booking-property-calendar-date-list",
    ),
    path(
        "properties/<uuid:property_id>/calendar/block/",
        PropertyCalendarDateBlockView.as_view(),
        name="booking-property-calendar-date-block",
    ),
    path(
        "properties/<uuid:property_id>/calendar/unblock/",
        PropertyCalendarDateUnblockView.as_view(),
        name="booking-property-calendar-date-unblock",
    ),
    path(
        "properties/<uuid:property_id>/calendar/hold/",
        PropertyCalendarDateHoldView.as_view(),
        name="booking-property-calendar-date-hold",
    ),
    path(
        "properties/<uuid:property_id>/calendar/unhold/",
        PropertyCalendarDateUnholdView.as_view(),
        name="booking-property-calendar-date-unhold",
    ),
    path(
        "client/",
        ClientBookingListCreateView.as_view(),
        name="client-booking-list-create",
    ),
    path(
        "client/<uuid:booking_id>/",
        ClientBookingDetailView.as_view(),
        name="client-booking-detail",
    ),
    path(
        "client/history/",
        ClientBookingHistoryListView.as_view(),
        name="client-booking-history-list",
    ),
    path(
        "client/history/<uuid:booking_id>/",
        ClientBookingHistoryDetailView.as_view(),
        name="client-booking-history-detail",
    ),
    path(
        "client/<uuid:booking_id>/cancel/",
        ClientBookingCancelView.as_view(),
        name="client-booking-cancel",
    ),
    path(
        "partner/<uuid:booking_id>/accept/",
        PartnerBookingAcceptView.as_view(),
        name="partner-booking-accept",
    ),
    path(
        "partner/<uuid:booking_id>/cancel/",
        PartnerBookingCancelView.as_view(),
        name="partner-booking-cancel",
    ),
    path(
        "partner/",
        PartnerBookingListView.as_view(),
        name="partner-booking-list",
    ),
    path(
        "partner/<uuid:booking_id>/complete/",
        PartnerCompleteBookingView.as_view(),
        name="partner-booking-complete",
    ),
    path(
        "partner/<uuid:booking_id>/no_show/",
        PartnerNoShowBookingView.as_view(),
        name="partner-booking-no-show",
    ),
    path(
        "admin/bookings/",
        AdminBookingListView.as_view(),
        name="admin-booking-list",
    ),
]
