# Generated by Django 5.2.9 on 2026-02-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('stories', '0001_initial'),
        ('users', '0006_remove_client_deleted_at_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DELETE FROM stories_storyview WHERE deleted_at IS NOT NULL;
            DELETE FROM stories_storymedia WHERE deleted_at IS NOT NULL;
            DELETE FROM stories_story WHERE deleted_at IS NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveConstraint(
            model_name='storyview',
            name='unique_story_client_story_view',
        ),
        migrations.RemoveField(
            model_name='story',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='storymedia',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='storyview',
            name='deleted_at',
        ),
        migrations.AddConstraint(
            model_name='storyview',
            constraint=models.UniqueConstraint(fields=('story', 'client'), name='unique_story_client_story_view'),
        ),
    ]
