-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2iFjf1EAbzn8z0L7
FHb6da4IW/T7E/1LIddNmzUkLaCgCgYIKoZIzj0DAQehRANCAARauui2PULRkFau
F6KHdd6Fwrs4qbCHDpnP7ZMmUz+y+gzroOqO2rMiuRp3jQwkuDS6zZGdH+nM7mBf
z/mNZHc1
-----END PRIVATE KEY-----