# Generated by Django 5.2.9 on 2026-03-17 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "legacy_client_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("legacy_client_guid", models.UUIDField(unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(db_index=True, max_length=16)),
                ("is_active", models.BooleanField(db_default=True, default=True)),
            ],
            options={
                "verbose_name": "Normalized customer",
                "verbose_name_plural": "Normalized customers",
                "db_table": "norm_customers",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "legacy_partner_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("legacy_partner_guid", models.UUIDField(unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("phone_number", models.CharField(db_index=True, max_length=16)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                ("is_verified", models.BooleanField(db_default=False, default=False)),
                ("verified_by_admin_id", models.IntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Normalized partner",
                "verbose_name_plural": "Normalized partners",
                "db_table": "norm_partners",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "legacy_plum_transaction_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("legacy_plum_transaction_guid", models.UUIDField(unique=True)),
                (
                    "provider_transaction_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("provider_hold_id", models.CharField(max_length=255, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("type", models.CharField(max_length=4)),
                ("status", models.CharField(max_length=20)),
                ("card_id", models.CharField(blank=True, max_length=255, null=True)),
                ("extra_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Normalized payment transaction",
                "verbose_name_plural": "Normalized payment transactions",
                "db_table": "norm_payment_transactions",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "legacy_property_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("legacy_property_guid", models.UUIDField(unique=True)),
                ("title", models.CharField(max_length=75)),
                ("currency", models.CharField(max_length=3)),
                ("verification_status", models.CharField(max_length=10)),
                ("is_verified", models.BooleanField(db_default=False, default=False)),
                ("is_archived", models.BooleanField(db_default=False, default=False)),
                ("region_id", models.BigIntegerField(blank=True, null=True)),
                ("district_id", models.BigIntegerField(blank=True, null=True)),
                ("shaharcha_id", models.BigIntegerField(blank=True, null=True)),
                ("mahalla_id", models.BigIntegerField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=14, max_digits=17, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=14, max_digits=17, null=True
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="normalized.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Normalized property",
                "verbose_name_plural": "Normalized properties",
                "db_table": "norm_properties",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "legacy_booking_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("legacy_booking_guid", models.UUIDField(unique=True)),
                ("booking_number", models.CharField(max_length=7, unique=True)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("adults", models.PositiveSmallIntegerField(default=1)),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("babies", models.PositiveSmallIntegerField(default=0)),
                ("current_status", models.CharField(db_index=True, max_length=20)),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent", models.BooleanField(db_default=False, default=False)),
                (
                    "payment_reminder_stage",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="normalized.customer",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="normalized.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Normalized booking",
                "verbose_name_plural": "Normalized bookings",
                "db_table": "norm_bookings",
            },
        ),
        migrations.CreateModel(
            name="PropertyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "legacy_property_price_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("month_from", models.DateField()),
                ("month_to", models.DateField()),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "price_on_working_days",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "price_on_weekends",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="normalized.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Normalized property price",
                "verbose_name_plural": "Normalized property prices",
                "db_table": "norm_property_prices",
            },
        ),
        migrations.CreateModel(
            name="BookingStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("from_status", models.CharField(blank=True, max_length=20, null=True)),
                ("to_status", models.CharField(db_index=True, max_length=20)),
                ("reason", models.CharField(blank=True, max_length=100, null=True)),
                ("source", models.CharField(default="legacy_sync", max_length=32)),
                ("changed_at", models.DateTimeField(db_index=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="normalized.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Normalized booking status history",
                "verbose_name_plural": "Normalized booking status history",
                "db_table": "norm_booking_status_history",
                "indexes": [
                    models.Index(
                        fields=["booking", "changed_at"], name="norm_booking_hist_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "to_status", "changed_at", "source"),
                        name="norm_booking_status_history_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "legacy_notification_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                (
                    "legacy_partner_notification_id",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("notification_type", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=15)),
                ("is_broadcast", models.BooleanField(db_default=False, default=False)),
                ("is_read", models.BooleanField(db_default=False, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="normalized.customer",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="normalized.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Normalized notification",
                "verbose_name_plural": "Normalized notifications",
                "db_table": "norm_notifications",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("customer__isnull", True),
                                ("is_broadcast", True),
                                ("partner__isnull", True),
                            ),
                            models.Q(
                                ("customer__isnull", False),
                                ("is_broadcast", False),
                                ("partner__isnull", True),
                            ),
                            models.Q(
                                ("customer__isnull", True),
                                ("is_broadcast", False),
                                ("partner__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="norm_notification_recipient_consistency",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BookingPaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "legacy_booking_transaction_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_links",
                        to="normalized.booking",
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_links",
                        to="normalized.paymenttransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Normalized booking payment link",
                "verbose_name_plural": "Normalized booking payment links",
                "db_table": "norm_booking_payment_links",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("booking", "payment_transaction"),
                        name="norm_booking_payment_link_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_out__gt", models.F("check_in"))),
                name="norm_booking_check_out_after_check_in",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("month_to__gte", models.F("month_from"))),
                name="norm_property_price_valid_range",
            ),
        ),
    ]
