# Generated by Django 5.2.9 on 2026-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("normalized", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookingpaymentlink",
            name="norm_booking_payment_link_unique",
        ),
    ]
