from django.urls import path
from apps.b2b.auth_views import B2BLoginSendOTPView, B2BLoginVerifyView
from apps.b2b.views import (
    ActiveTripEmployeesView,
    B2BCompanyView,
    B2BDepartmentListCreateView,
    B2BDepartmentDetailView,
    B2BDepartmentMoveEmployeesView,
    B2BEmployeeLimitsView,
    B2BEmployeeListCreateView,
    B2BEmployeePassportPreviewView,
    B2BEmployeePassportPreviewStatusView,
    B2BEmployeeRetrieveUpdateView,
    B2BHotelBookingDetailView,
    B2BHotelBookingCancelView,
    B2BHotelBookingListCreateView,
    B2BHotelCalendarView,
    B2BHotelCardView,
    B2BHotelRecommendationsView,
    B2BHotelRoomsView,
    B2BHotelSearchView,
    B2BLeadRequestCreateView,
    B2BStatisticsView,
    B2BMonthlySpendingChartView,
    B2BStatisticsChartView,
    B2BWeeklySpendingChartView,
    BusinessTripListCreateView,
    BusinessTripRetrieveUpdateView,
    DashboardNotificationsView,
    DashboardSummaryView,
    DepartmentMonthlySpendingView,
    RecentTripEmployeesView,
    TopEmployeesByTripsView,
    TopHotelsByBookingsView,
    HotelMonthlySummaryView,
    TripStatusSummaryView,
    TravelLimitDetailView,
    TravelLimitsView,
    TripEmployeeListCreateView,
    TravelPolicyView,
    BudgetRequestListCreateView,
    BudgetRequestReviewView,
    TransactionListView,
    TripVoucherView,
)

urlpatterns = [
    path("auth/login/", B2BLoginSendOTPView.as_view(), name="b2b-login"),
    path("auth/login/verify/", B2BLoginVerifyView.as_view(), name="b2b-login-verify"),
    path("lead-requests/", B2BLeadRequestCreateView.as_view(), name="b2b-lead-requests"),
    path("company/", B2BCompanyView.as_view(), name="b2b-company"),
    path("hotels/search/", B2BHotelSearchView.as_view(), name="b2b-hotel-search"),
    path("hotels/bookings/", B2BHotelBookingListCreateView.as_view(), name="b2b-hotel-bookings"),
    path("hotels/bookings/<int:booking_id>/", B2BHotelBookingDetailView.as_view(), name="b2b-hotel-booking-detail"),
    path("hotels/bookings/<int:booking_id>/cancel/", B2BHotelBookingCancelView.as_view(), name="b2b-hotel-booking-cancel"),
    path("hotels/top-by-bookings/", TopHotelsByBookingsView.as_view(), name="b2b-hotels-top-by-bookings"),
    path("hotels/monthly-summary/", HotelMonthlySummaryView.as_view(), name="b2b-hotels-monthly-summary"),
    path("hotels/recommendations/", B2BHotelRecommendationsView.as_view(), name="b2b-hotels-recommendations"),
    path("hotels/<str:hotel_guid>/calendar/", B2BHotelCalendarView.as_view(), name="b2b-hotel-calendar"),
    path("hotels/<str:hotel_guid>/rooms/", B2BHotelRoomsView.as_view(), name="b2b-hotel-rooms"),
    path("hotels/<str:hotel_guid>/card/", B2BHotelCardView.as_view(), name="b2b-hotel-card"),
    path("departments/", B2BDepartmentListCreateView.as_view(), name="b2b-departments"),
    path("departments/monthly-spending/", DepartmentMonthlySpendingView.as_view(), name="b2b-departments-monthly-spending"),
    path("departments/<int:department_id>/", B2BDepartmentDetailView.as_view(), name="b2b-department-detail"),
    path("departments/<int:department_id>/move-employees/", B2BDepartmentMoveEmployeesView.as_view(), name="b2b-department-move-employees"),
    path("employees/", B2BEmployeeListCreateView.as_view(), name="b2b-employees"),
    path("employees/limits/", B2BEmployeeLimitsView.as_view(), name="b2b-employees-limits"),
    path("employees/passport-preview/", B2BEmployeePassportPreviewView.as_view(), name="b2b-employee-passport-preview"),
    path("employees/passport-preview/<str:job_id>/", B2BEmployeePassportPreviewStatusView.as_view(), name="b2b-employee-passport-preview-status"),
    path("employees/<int:employee_id>/", B2BEmployeeRetrieveUpdateView.as_view(), name="b2b-employee-detail"),
    path("employees/top-by-trips/", TopEmployeesByTripsView.as_view(), name="b2b-employees-top-by-trips"),
    path("trips/", BusinessTripListCreateView.as_view(), name="b2b-trips"),
    path("trips/<int:trip_id>/", BusinessTripRetrieveUpdateView.as_view(), name="b2b-trip-detail"),
    path("trips/<int:trip_id>/employees/", TripEmployeeListCreateView.as_view(), name="b2b-trip-employees"),
    path("trips/<int:trip_id>/voucher/", TripVoucherView.as_view(), name="b2b-trip-voucher"),
    path("trips/active-employees/", ActiveTripEmployeesView.as_view(), name="b2b-active-trip-employees"),
    path("trips/status-summary/", TripStatusSummaryView.as_view(), name="b2b-trip-status-summary"),
    path("recent-trips/employees/", RecentTripEmployeesView.as_view(), name="b2b-recent-trip-employees"),
    path("travel-policy/", TravelPolicyView.as_view(), name="b2b-travel-policy"),
    path("travel-policy/limits/", TravelLimitsView.as_view(), name="b2b-travel-policy-limits"),
    path("travel-policy/limits/<int:rule_id>/", TravelLimitDetailView.as_view(), name="b2b-travel-policy-limit-detail"),
    path("budget-requests/", BudgetRequestListCreateView.as_view(), name="b2b-budget-requests"),
    path("budget-requests/<int:request_id>/review/", BudgetRequestReviewView.as_view(), name="b2b-budget-request-review"),
    path("transactions/", TransactionListView.as_view(), name="b2b-transactions"),
    path("statistics/", B2BStatisticsView.as_view(), name="b2b-statistics"),
    path("statistics/chart/", B2BStatisticsChartView.as_view(), name="b2b-statistics-chart"),
    path("statistics/monthly-chart/", B2BMonthlySpendingChartView.as_view(), name="b2b-statistics-monthly-chart"),
    path("statistics/weekly-chart/", B2BWeeklySpendingChartView.as_view(), name="b2b-statistics-weekly-chart"),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="b2b-dashboard-summary"),
    path("dashboard/notifications/", DashboardNotificationsView.as_view(), name="b2b-dashboard-notifications"),
]
