from django.urls import path
from apps.b2b.auth_views import B2BLoginSendOTPView, B2BLoginVerifyView
from apps.b2b.views import (
    ActiveTripEmployeesView,
    B2BCompanyView,
    B2BDepartmentListCreateView,
    B2BEmployeeListCreateView,
    B2BEmployeeRetrieveUpdateView,
    B2BHotelBookingDetailView,
    B2BHotelBookingListCreateView,
    B2BHotelRoomsView,
    B2BHotelSearchView,
    B2BStatisticsView,
    BusinessTripListCreateView,
    BusinessTripRetrieveUpdateView,
    DashboardSummaryView,
    DepartmentMonthlySpendingView,
    DepartmentTravelLimitDetailView,
    DepartmentTravelLimitsView,
    EmployeeTravelLimitDetailView,
    EmployeeTravelLimitsView,
    GlobalTravelLimitView,
    RecentTripEmployeesView,
    TripEmployeeListCreateView,
    TravelPolicyView,
    BudgetRequestListCreateView,
    BudgetRequestReviewView,
    TripVoucherView,
)

urlpatterns = [
    path("auth/login/", B2BLoginSendOTPView.as_view(), name="b2b-login"),
    path("auth/login/verify/", B2BLoginVerifyView.as_view(), name="b2b-login-verify"),
    path("company/", B2BCompanyView.as_view(), name="b2b-company"),
    path("hotels/search/", B2BHotelSearchView.as_view(), name="b2b-hotel-search"),
    path("hotels/bookings/", B2BHotelBookingListCreateView.as_view(), name="b2b-hotel-bookings"),
    path("hotels/bookings/<int:booking_id>/", B2BHotelBookingDetailView.as_view(), name="b2b-hotel-booking-detail"),
    path("hotels/<str:hotel_guid>/rooms/", B2BHotelRoomsView.as_view(), name="b2b-hotel-rooms"),
    path("departments/", B2BDepartmentListCreateView.as_view(), name="b2b-departments"),
    path("departments/monthly-spending/", DepartmentMonthlySpendingView.as_view(), name="b2b-departments-monthly-spending"),
    path("employees/", B2BEmployeeListCreateView.as_view(), name="b2b-employees"),
    path("employees/<int:employee_id>/", B2BEmployeeRetrieveUpdateView.as_view(), name="b2b-employee-detail"),
    path("trips/", BusinessTripListCreateView.as_view(), name="b2b-trips"),
    path("trips/<int:trip_id>/", BusinessTripRetrieveUpdateView.as_view(), name="b2b-trip-detail"),
    path("trips/<int:trip_id>/employees/", TripEmployeeListCreateView.as_view(), name="b2b-trip-employees"),
    path("trips/<int:trip_id>/voucher/", TripVoucherView.as_view(), name="b2b-trip-voucher"),
    path("trips/active-employees/", ActiveTripEmployeesView.as_view(), name="b2b-active-trip-employees"),
    path("recent-trips/employees/", RecentTripEmployeesView.as_view(), name="b2b-recent-trip-employees"),
    path("travel-policy/", TravelPolicyView.as_view(), name="b2b-travel-policy"),
    path("travel-policy/limits/global/", GlobalTravelLimitView.as_view(), name="b2b-travel-policy-limit-global"),
    path("travel-policy/limits/departments/", DepartmentTravelLimitsView.as_view(), name="b2b-travel-policy-limit-departments"),
    path("travel-policy/limits/departments/<int:rule_id>/", DepartmentTravelLimitDetailView.as_view(), name="b2b-travel-policy-limit-department-detail"),
    path("travel-policy/limits/employees/", EmployeeTravelLimitsView.as_view(), name="b2b-travel-policy-limit-employees"),
    path("travel-policy/limits/employees/<int:rule_id>/", EmployeeTravelLimitDetailView.as_view(), name="b2b-travel-policy-limit-employee-detail"),
    path("budget-requests/", BudgetRequestListCreateView.as_view(), name="b2b-budget-requests"),
    path("budget-requests/<int:request_id>/review/", BudgetRequestReviewView.as_view(), name="b2b-budget-request-review"),
    path("statistics/", B2BStatisticsView.as_view(), name="b2b-statistics"),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="b2b-dashboard-summary"),
]
