from django.urls import include, path
from apps.b2b.auth_views import (
    B2BLoginSendOTPView,
    B2BLoginVerifyView,
    B2BLogoutView,
    B2BTokenRefreshView,
)
from apps.b2b.views import (
    ActiveTripEmployeesView,
    B2BCompanyView,
    B2BDepartmentListCreateView,
    B2BDepartmentDetailView,
    B2BDepartmentMoveEmployeesView,
    B2BEmployeeLimitsView,
    B2BEmployeeListCreateView,
    B2BEmployeePassportPreviewView,
    B2BEmployeePassportPreviewStatusView,
    B2BEmployeeRetrieveUpdateView,
    B2BLeadRequestCreateView,
    B2BStatisticsView,
    B2BMonthlySpendingChartView,
    B2BStatisticsChartView,
    B2BWeeklySpendingChartView,
    BusinessTripListCreateView,
    BusinessTripRetrieveUpdateView,
    DashboardNotificationsView,
    DashboardSummaryView,
    DepartmentMonthlySpendingView,
    RecentTripEmployeesView,
    TopEmployeesByTripsView,
    TripStatusSummaryView,
    TravelLimitDetailView,
    TravelLimitsView,
    TripEmployeeListCreateView,
    TravelPolicyView,
    BudgetRequestListCreateView,
    BudgetRequestReviewView,
    TransactionListView,
    TripVoucherView,
)

urlpatterns = [
    # The mobile app for a company's own staff — separate identity (employee,
    # not dashboard user) and its own role rules, so it gets its own namespace.
    path("workspace/", include("apps.b2b.workspace.urls")),
    # Meta's own two callbacks — the OAuth redirect and the leadgen webhook.
    # Deliberately outside `workspace/`: neither carries a workspace login,
    # and burying them under a namespace that otherwise always requires one
    # would be misleading. See `apps/b2b/integrations/public_urls.py`.
    path("integrations/", include("apps.b2b.integrations.public_urls")),
    path("auth/login/", B2BLoginSendOTPView.as_view(), name="b2b-login"),
    path("auth/login/verify/", B2BLoginVerifyView.as_view(), name="b2b-login-verify"),
    path("auth/token/refresh/", B2BTokenRefreshView.as_view(), name="b2b-token-refresh"),
    path("auth/logout/", B2BLogoutView.as_view(), name="b2b-logout"),
    path("lead-requests/", B2BLeadRequestCreateView.as_view(), name="b2b-lead-requests"),
    path("company/", B2BCompanyView.as_view(), name="b2b-company"),
    path("departments/", B2BDepartmentListCreateView.as_view(), name="b2b-departments"),
    path("departments/monthly-spending/", DepartmentMonthlySpendingView.as_view(), name="b2b-departments-monthly-spending"),
    path("departments/<int:department_id>/", B2BDepartmentDetailView.as_view(), name="b2b-department-detail"),
    path("departments/<int:department_id>/move-employees/", B2BDepartmentMoveEmployeesView.as_view(), name="b2b-department-move-employees"),
    path("employees/", B2BEmployeeListCreateView.as_view(), name="b2b-employees"),
    path("employees/limits/", B2BEmployeeLimitsView.as_view(), name="b2b-employees-limits"),
    path("employees/passport-preview/", B2BEmployeePassportPreviewView.as_view(), name="b2b-employee-passport-preview"),
    path("employees/passport-preview/<str:job_id>/", B2BEmployeePassportPreviewStatusView.as_view(), name="b2b-employee-passport-preview-status"),
    path("employees/<int:employee_id>/", B2BEmployeeRetrieveUpdateView.as_view(), name="b2b-employee-detail"),
    path("employees/top-by-trips/", TopEmployeesByTripsView.as_view(), name="b2b-employees-top-by-trips"),
    path("trips/", BusinessTripListCreateView.as_view(), name="b2b-trips"),
    path("trips/<int:trip_id>/", BusinessTripRetrieveUpdateView.as_view(), name="b2b-trip-detail"),
    path("trips/<int:trip_id>/employees/", TripEmployeeListCreateView.as_view(), name="b2b-trip-employees"),
    path("trips/<int:trip_id>/voucher/", TripVoucherView.as_view(), name="b2b-trip-voucher"),
    path("trips/active-employees/", ActiveTripEmployeesView.as_view(), name="b2b-active-trip-employees"),
    path("trips/status-summary/", TripStatusSummaryView.as_view(), name="b2b-trip-status-summary"),
    path("recent-trips/employees/", RecentTripEmployeesView.as_view(), name="b2b-recent-trip-employees"),
    path("travel-policy/", TravelPolicyView.as_view(), name="b2b-travel-policy"),
    path("travel-policy/limits/", TravelLimitsView.as_view(), name="b2b-travel-policy-limits"),
    path("travel-policy/limits/<int:rule_id>/", TravelLimitDetailView.as_view(), name="b2b-travel-policy-limit-detail"),
    path("budget-requests/", BudgetRequestListCreateView.as_view(), name="b2b-budget-requests"),
    path("budget-requests/<int:request_id>/review/", BudgetRequestReviewView.as_view(), name="b2b-budget-request-review"),
    path("transactions/", TransactionListView.as_view(), name="b2b-transactions"),
    path("statistics/", B2BStatisticsView.as_view(), name="b2b-statistics"),
    path("statistics/chart/", B2BStatisticsChartView.as_view(), name="b2b-statistics-chart"),
    path("statistics/monthly-chart/", B2BMonthlySpendingChartView.as_view(), name="b2b-statistics-monthly-chart"),
    path("statistics/weekly-chart/", B2BWeeklySpendingChartView.as_view(), name="b2b-statistics-weekly-chart"),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="b2b-dashboard-summary"),
    path("dashboard/notifications/", DashboardNotificationsView.as_view(), name="b2b-dashboard-notifications"),
]
