# Generated by Django 5.2.9 on 2026-03-13 11:03

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Firstname and Lastname must be 3–64 characters long",
                                regex="^[A-Za-zА-Яа-яЁё]{3,255}$",
                            )
                        ],
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Firstname and Lastname must be 3–64 characters long",
                                regex="^[A-Za-zА-Яа-яЁё]{3,255}$",
                            )
                        ],
                        verbose_name="Last name",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number should start with +998",
                                regex="^\\+?998\\d{9}$",
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "avatar",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="users/avatars/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "heif", "heic"]
                            )
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_default=True, default=True, verbose_name="Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number should start with +998",
                                regex="^\\+?998\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("CL_LGN", "Login"),
                            ("CL_RGR", "Register"),
                            ("PR_LGN", "Partner Login"),
                            ("PR_RGR", "Partner Register"),
                        ],
                        max_length=6,
                    ),
                ),
                ("is_sent", models.BooleanField(db_default=True, default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="FCM token"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        max_length=10,
                        verbose_name="Device type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="users.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client device",
                "verbose_name_plural": "Client devices",
                "db_table": "client_devices",
            },
        ),
        migrations.CreateModel(
            name="ClientSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "device_id",
                    models.CharField(blank=True, null=True, verbose_name="Device ID"),
                ),
                ("user_agent", models.CharField(verbose_name="User agent")),
                ("last_ip", models.GenericIPAddressField(verbose_name="Last IP")),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client session",
                "verbose_name_plural": "Client sessions",
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        blank=True,
                        db_default=False,
                        default=False,
                        null=True,
                        verbose_name="Verified",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified at"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Firstname and Lastname must be 3–64 characters long",
                                regex="^[A-Za-zА-Яа-яЁё]{3,255}$",
                            )
                        ],
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Firstname and Lastname must be 3–64 characters long",
                                regex="^[A-Za-zА-Яа-яЁё]{3,255}$",
                            )
                        ],
                        verbose_name="Last name",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username must be 3–32 characters long",
                                regex="^[a-zA-Z0-9_]{3,255}$",
                            )
                        ],
                        verbose_name="Username",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number should start with +998",
                                regex="^\\+?998\\d{9}$",
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "avatar",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="users/avatars/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "heif", "heic"]
                            )
                        ],
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Email verified"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_default=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.CreateModel(
            name="PartnerDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="FCM token"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        max_length=10,
                        verbose_name="Device type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="users.partner",
                        verbose_name="Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner device",
                "verbose_name_plural": "Partner devices",
                "db_table": "partner_devices",
            },
        ),
        migrations.CreateModel(
            name="PartnerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="users/documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "png"]
                            )
                        ],
                        verbose_name="Document",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CERT", "Certificate"), ("PASS", "Passport")],
                        max_length=4,
                        verbose_name="Type",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Is verified"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified at"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.partner",
                        verbose_name="Partner",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner document",
                "verbose_name_plural": "Partner documents",
            },
        ),
        migrations.CreateModel(
            name="PartnerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "device_id",
                    models.CharField(blank=True, null=True, verbose_name="Device ID"),
                ),
                ("user_agent", models.CharField(verbose_name="User agent")),
                ("last_ip", models.GenericIPAddressField(verbose_name="Last IP")),
                (
                    "partner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.partner",
                        verbose_name="Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner session",
                "verbose_name_plural": "Partner sessions",
            },
        ),
        migrations.CreateModel(
            name="PartnerTelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "telegram_user_id",
                    models.BigIntegerField(db_index=True, unique=True),
                ),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "partner",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram",
                        to="users.partner",
                        verbose_name="Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Telegram user",
                "verbose_name_plural": "Partner Telegram users",
            },
        ),
        migrations.AddConstraint(
            model_name="partner",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="unique_username_ci",
            ),
        ),
    ]
