# Generated by Django 5.2.9 on 2026-03-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Keep as a no-op to avoid table-name divergence from model Meta.db_table.
        migrations.RunSQL(sql=migrations.RunSQL.noop, reverse_sql=migrations.RunSQL.noop),
    ]
