# Generated by Django 5.2.12 on 2026-03-18 08:52

from django.db import migrations


def create_partnersession_table(apps, schema_editor):
    """Create users_partnersession if it doesn't exist (e.g. migration was faked or table dropped)."""
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = 'users_partnersession'
        """)
        if cursor.fetchone():
            return
        cursor.execute("""
            CREATE TABLE "users_partnersession" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "guid" uuid NOT NULL UNIQUE,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "device_id" varchar NULL,
                "user_agent" varchar NOT NULL,
                "last_ip" inet NOT NULL,
                "partner_id" bigint NULL REFERENCES "users_partner" ("id") DEFERRABLE INITIALLY DEFERRED
            )
        """)
        cursor.execute('CREATE INDEX IF NOT EXISTS "users_partnersession_partner_id_aae6e1a1" ON "users_partnersession" ("partner_id")')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_partnersession_table, noop),
    ]
