# Generated by Django 5.2.9 on 2026-03-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_partnersession_if_missing'),
        ('users', '0002_alter_clientdevice_table_alter_clientsession_table_and_more'),
    ]

    operations = [
    ]
