# Generated by Django 5.2.12 on 2026-03-31 06:15

from django.db import migrations


def create_clientsession_table(apps, schema_editor):
    """Create users_clientsession if it is missing (e.g., migration was faked or table dropped)."""

    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return

    table_name = apps.get_model("users", "ClientSession")._meta.db_table

    with connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass(%s)", [table_name])
        regclass = cursor.fetchone()[0]
        if regclass:
            return

        cursor.execute(
            f'''
            CREATE TABLE IF NOT EXISTS "{table_name}" (
                "id" bigserial PRIMARY KEY,
                "guid" uuid NOT NULL UNIQUE,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "device_id" varchar NULL,
                "user_agent" varchar NOT NULL,
                "last_ip" inet NOT NULL,
                "client_id" bigint NULL REFERENCES "users_client" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
            )
            '''
        )
        cursor.execute(
            f'''
            CREATE INDEX IF NOT EXISTS "{table_name}_client_id_14bbfe45"
            ON "{table_name}" ("client_id")
            '''
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_merge_20260324_0033"),
    ]

    operations = [
        migrations.RunPython(create_clientsession_table, migrations.RunPython.noop),
    ]
