# Generated by Django 5.2.12 on 2026-03-31 11:05

from django.db import migrations


def create_clientdevice_table(apps, schema_editor):
    """
    Create client_devices table if it is missing (e.g., faked migrations or table was dropped).
    """
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return

    table_name = apps.get_model("users", "ClientDevice")._meta.db_table

    with connection.cursor() as cursor:
        cursor.execute("SELECT to_regclass(%s)", [table_name])
        regclass = cursor.fetchone()[0]
        if regclass:
            return

        cursor.execute(
            f"""
            CREATE TABLE IF NOT EXISTS "{table_name}" (
                "id" bigserial PRIMARY KEY,
                "guid" uuid NOT NULL UNIQUE,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "fcm_token" varchar(255) NOT NULL UNIQUE,
                "device_type" varchar(10) NOT NULL,
                "is_active" boolean NOT NULL DEFAULT true,
                "client_id" bigint NOT NULL
                    REFERENCES "users_client" ("id")
                    ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
            );
            """
        )
        cursor.execute(
            f"""
            CREATE UNIQUE INDEX IF NOT EXISTS "{table_name}_fcm_token_1e0903d2_like"
            ON "{table_name}" ("fcm_token");
            """
        )
        return

    ClientDevice = apps.get_model("users", "ClientDevice")
    schema_editor.create_model(ClientDevice)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_clientsession_if_missing"),
    ]

    operations = [
        migrations.RunPython(create_clientdevice_table, migrations.RunPython.noop),
    ]
