# Generated by Django 5.2.12 on 2026-04-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_clientdevice_if_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='purpose',
            field=models.CharField(choices=[('CL_LGN', 'Login'), ('CL_RGR', 'Register'), ('PR_LGN', 'Partner Login'), ('PR_RGR', 'Partner Register'), ('PR_RMD', 'Partner Property Reminder')], max_length=6),
        ),
    ]
