# Generated by Django 5.2.9 on 2026-03-13 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booking_new", "New Booking"),
                            ("booking_confirmed", "Booking Confirmed"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("booking_completed", "Booking Completed"),
                            ("booking_no_show", "Booking No Show"),
                            ("system", "System"),
                            ("promo", "Promotion"),
                        ],
                        default="system",
                        max_length=30,
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data like booking_id, etc.",
                        verbose_name="Data",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="users.partner",
                        verbose_name="Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Notification",
                "verbose_name_plural": "Partner Notifications",
                "db_table": "partner_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "push_message",
                    models.TextField(null=True, verbose_name="Push message"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "Booking confirmed"),
                            ("booking_cancelled", "Booking cancelled"),
                            ("reminder", "Reminder"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent")],
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_for_every_one",
                    models.BooleanField(default=False, verbose_name="Is for everyone"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="users.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("is_for_every_one", True), ("recipient__isnull", True)
                            ),
                            models.Q(
                                ("is_for_every_one", False),
                                ("recipient__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="notification_recipient_consistency",
                    )
                ],
            },
        ),
    ]
