# Generated by Django 5.2.9 on 2026-03-13 12:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    # PartnerNotification is already created by 0001_initial.
    # Keep this migration as a no-op to preserve migration history compatibility.
    operations = []
