from django.urls import path

from .views import (
    PropertyTypeListView,
    PropertyFilterByLinkView,
    ApartmentPropertyListCreateView,
    CottagePropertyListCreateView,
    RegionPropertyListView,
    PropertyImageCreateView,
    PropertyServiceListView,
    PropertyReviewListCreateView,
    PropertyImageUpdateDeleteView,
    PropertyRetrieveUpdateDestroyView,
    PartnerPropertyReviewListView,
    PartnerPropertyListView,
    ApartmentPartnerPropertyListView,
    CottagePartnerPropertyListView,
    SavedPropertyListView,
    PropertyFavoriteToggleView,
    RegionListView,
    DistrictListView,
    PrefectureListView,
    LocationListView,
    PrefectureListView,
    UnifiedRecommendationsListView,
    CategoryListView,
    CategoryPropertyRecommendationView,
    CategoryLatestPropertyListView,
    PropertyListCreateView,
)


urlpatterns = [
    path("types/", PropertyTypeListView.as_view(), name="property-type-list"),
    path("location/", LocationListView.as_view(), name="location"),
    path("regions/", RegionListView.as_view(), name="region-list"),
    path(
        "regions/<uuid:region_id>/properties/",
        RegionPropertyListView.as_view(),
        name="region-property-list",
    ),
    path("districts/", DistrictListView.as_view(), name="district-list"),
    path("prefectures/", PrefectureListView.as_view(), name="prefecture-list"),
    path("services/", PropertyServiceListView.as_view(), name="property-service-list"),
    path(
        "recommendations/",
        UnifiedRecommendationsListView.as_view(),
        name="property-recommendations",
    ),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path(
        "categories/<uuid:category_id>/properties/latest/",
        CategoryLatestPropertyListView.as_view(),
        name="category-latest-properties",
    ),
    path(
        "categories/<uuid:category_id>/properties/",
        CategoryPropertyRecommendationView.as_view(),
        name="category-property-recommendation",
    ),
    path("properties/", PropertyListCreateView.as_view(), name="property-list-create"),
    path(
        "apartment/",
        ApartmentPropertyListCreateView.as_view(),
        name="apartment-property-list-create-legacy",
    ),
    path(
        "apartments/",
        ApartmentPropertyListCreateView.as_view(),
        name="apartment-property-list-create",
    ),
    path(
        "apartments/<uuid:property_id>/",
        PropertyRetrieveUpdateDestroyView.as_view(),
        name="apartment-property-retrieve-update-destroy",
    ),
    path(
        "apartments/<uuid:property_id>/favorite/",
        PropertyFavoriteToggleView.as_view(),
        name="apartment-property-favorite-toggle",
    ),
    path(
        "apartments/<uuid:property_id>/images/",
        PropertyImageCreateView.as_view(),
        name="apartment-property-image-create",
    ),
    path(
        "apartments/<uuid:property_id>/images/<uuid:image_id>/",
        PropertyImageUpdateDeleteView.as_view(),
        name="apartment-property-image-update-delete",
    ),
    path(
        "apartments/<uuid:property_id>/reviews/",
        PropertyReviewListCreateView.as_view(),
        name="apartment-property-review-list-create",
    ),
    path(
        "apartments/<uuid:property_id>/partner/reviews/",
        PartnerPropertyReviewListView.as_view(),
        name="apartment-partner-property-reviews",
    ),
    path(
        "cottages/",
        CottagePropertyListCreateView.as_view(),
        name="cottage-property-list-create",
    ),
    path(
        "cottages/<uuid:property_id>/",
        PropertyRetrieveUpdateDestroyView.as_view(),
        name="cottage-property-retrieve-update-destroy",
    ),
    path(
        "cottages/<uuid:property_id>/favorite/",
        PropertyFavoriteToggleView.as_view(),
        name="cottage-property-favorite-toggle",
    ),
    path(
        "cottages/<uuid:property_id>/images/",
        PropertyImageCreateView.as_view(),
        name="cottage-property-image-create",
    ),
    path(
        "cottages/<uuid:property_id>/images/<uuid:image_id>/",
        PropertyImageUpdateDeleteView.as_view(),
        name="cottage-property-image-update-delete",
    ),
    path(
        "cottages/<uuid:property_id>/reviews/",
        PropertyReviewListCreateView.as_view(),
        name="cottage-property-review-list-create",
    ),
    path(
        "cottages/<uuid:property_id>/partner/reviews/",
        PartnerPropertyReviewListView.as_view(),
        name="cottage-partner-property-reviews",
    ),
    path(
        "properties/favorites/",
        SavedPropertyListView.as_view(),
        name="saved-property-list",
    ),
    path(
        "properties/filter-by-link/",
        PropertyFilterByLinkView.as_view(),
        name="property-filter-by-link",
    ),
    path(
        "partner/properties/",
        PartnerPropertyListView.as_view(),
        name="partner-property-list",
    ),
    path(
        "partner/apartments/",
        ApartmentPartnerPropertyListView.as_view(),
        name="apartment-partner-property-list",
    ),
    path(
        "partner/cottages/",
        CottagePartnerPropertyListView.as_view(),
        name="cottage-partner-property-list",
    ),
]
