# Generated by Django 5.2.9 on 2026-02-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('booking', '0001_initial'),
        ('property', '0003_remove_property_unique_active_title_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DELETE FROM booking_bookingprice WHERE deleted_at IS NOT NULL;
            DELETE FROM booking_bookingtransaction WHERE deleted_at IS NOT NULL;
            DELETE FROM booking_booking WHERE deleted_at IS NOT NULL;
            DELETE FROM booking_calendardate WHERE deleted_at IS NOT NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveConstraint(
            model_name='calendardate',
            name='unique_property_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bookingprice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='bookingtransaction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='calendardate',
            name='deleted_at',
        ),
        migrations.AddConstraint(
            model_name='calendardate',
            constraint=models.UniqueConstraint(fields=('property', 'date'), name='unique_property_date'),
        ),
    ]
