# Generated by Django 5.2.12 on 2026-03-18 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlumTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('hold_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('HOLD', 'Hold'), ('CHRG', 'Charge')], max_length=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HOLD_CONFIRMED', 'Hold Confirmed'), ('CHARGED', 'Charged'), ('DISMISSED', 'Dismissed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('UZS', "Uzbekistan So'm")], db_default='USD', default='USD', max_length=3, verbose_name='Currency')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Rate')),
                ('date', models.DateField(auto_now=True, db_index=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Exchange rate',
                'verbose_name_plural': 'Exchange rates',
                'indexes': [models.Index(fields=['currency', 'date'], name='payment_exc_currenc_ccc57b_idx')],
                'constraints': [models.UniqueConstraint(fields=('currency', 'date'), name='unique_currency_date')],
            },
        ),
    ]
