# Generated by Django 5.2.9 on 2026-02-19 12:52

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        # NOTE:
        # Current payment 0001_initial does not define deleted_at columns on these tables.
        # Keep this migration as an explicit no-op to preserve migration numbering across environments.
        migrations.RunSQL(sql=migrations.RunSQL.noop, reverse_sql=migrations.RunSQL.noop),
    ]
