# Generated by Django 5.2.9 on 2026-03-08 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_conversation_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_convers_c2caf0_idx',
            old_name='chat_chatme_convers_1f53de_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_receive_745599_idx',
            old_name='chat_chatme_receive_576deb_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_receive_03b359_idx',
            old_name='chat_chatme_receive_4b35f8_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_admin_u_14821f_idx',
            old_name='chat_conver_admin_u_5fe4e0_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_partner_d729da_idx',
            old_name='chat_conver_partner_3d80c8_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver'], name='chat_messag_sender__61a5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read'], name='chat_messag_receive_14362e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='chat_messag_created_f18bb8_idx'),
        ),
    ]
